version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - elk
    environment:
      - ELASTIC_APM_SERVICE_NAME=message-app-v2
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - ELASTIC_APM_ENVIRONMENT=docker
      - ELASTIC_APM_LOG_LEVEL=debug

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../logs:/ /share/logstash/logs  # Mount Windows log directory
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    user: root
    entrypoint: ["sh", "-c", "chmod go-w /usr/share/filebeat/filebeat.yml && exec /usr/local/bin/docker-entrypoint filebeat"]  # Modify permissions and start filebeat
    volumes:
      - ../logs:/usr/share/filebeat/logs  # Mount Windows log directory
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elk

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.0
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
    ports:
      - "8200:8200"
    networks:
      - elk


volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge